//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fenix
{
    using System;
    using System.Collections.Generic;
    
    public partial class cdlMessageNumber
    {
        public int ID { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public int LastFreeNumber { get; set; }
    }
}
