//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

using System.Web.UI.HtmlControls;
using System.Web.UI.WebControls;

namespace Fenix {
    
    
    public partial class Kitting {
        
        /// <summary>
        /// liKittingManuallyOrder control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected HtmlGenericControl liKittingManuallyOrder;
        
        /// <summary>
        /// mnuKittingManuallyOrder control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected HyperLink mnuKittingManuallyOrder;
        
        /// <summary>
        /// liKittingReconciliation control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected HtmlGenericControl liKittingReconciliation;
        
        /// <summary>
        /// mnuKittingReconciliation control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected HyperLink mnuKittingReconciliation;
        
        /// <summary>
        /// liKittingBrowse control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected HtmlGenericControl liKittingBrowse;
        
        /// <summary>
        /// mnuKittingBrowse control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected HyperLink mnuKittingBrowse;
        
        /// <summary>
        /// liKittingApproval control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected HtmlGenericControl liKittingApproval;
        
        /// <summary>
        /// mnuKittingApproval control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected HyperLink mnuKittingApproval;
        
        /// <summary>
        /// liKittingCardStockItems control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected HtmlGenericControl liKittingCardStockItems;
        
        /// <summary>
        /// mnuKittingCardStockItems control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected HyperLink mnuKittingCardStockItems;
        
        /// <summary>
        /// MainContent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected ContentPlaceHolder MainContent;
    }
}
