//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.18444
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.0.30319.17929.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="reflexInterfacesWSSoapBinding", Namespace="http://www.hardis.fr/reflexInterfacesWS")]
public partial class reflexInterfacesWS : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback submitStructuredDataToProcessingsOperationCompleted;
    
    private System.Threading.SendOrPostCallback getStructuredDataFromProcessingsOperationCompleted;
    
    private System.Threading.SendOrPostCallback getStructuredDataFromProcessingsBasedOnMessageNumberOperationCompleted;
    
    /// <remarks/>
    public reflexInterfacesWS() {
        this.Url = "http://srvrfx2:8081/ereflex_CS_M/services/reflexInterfacesWS";
    }
    
    /// <remarks/>
    public event submitStructuredDataToProcessingsCompletedEventHandler submitStructuredDataToProcessingsCompleted;
    
    /// <remarks/>
    public event getStructuredDataFromProcessingsCompletedEventHandler getStructuredDataFromProcessingsCompleted;
    
    /// <remarks/>
    public event getStructuredDataFromProcessingsBasedOnMessageNumberCompletedEventHandler getStructuredDataFromProcessingsBasedOnMessageNumberCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://www.hardis.fr/reflexInterfacesWS", ResponseNamespace="http://www.hardis.fr/reflexInterfacesWS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("submitStructuredDataToProcessingsReturn")]
    public HWSITFAdeliaPrcnamSUBMIT_STRUCTURED_DATA_TO_PROCESSINGS00Result submitStructuredDataToProcessings(string login, string password, string partnerCode, string messageType, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] data, string characterEncoding) {
        object[] results = this.Invoke("submitStructuredDataToProcessings", new object[] {
                    login,
                    password,
                    partnerCode,
                    messageType,
                    data,
                    characterEncoding});
        return ((HWSITFAdeliaPrcnamSUBMIT_STRUCTURED_DATA_TO_PROCESSINGS00Result)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginsubmitStructuredDataToProcessings(string login, string password, string partnerCode, string messageType, byte[] data, string characterEncoding, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("submitStructuredDataToProcessings", new object[] {
                    login,
                    password,
                    partnerCode,
                    messageType,
                    data,
                    characterEncoding}, callback, asyncState);
    }
    
    /// <remarks/>
    public HWSITFAdeliaPrcnamSUBMIT_STRUCTURED_DATA_TO_PROCESSINGS00Result EndsubmitStructuredDataToProcessings(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((HWSITFAdeliaPrcnamSUBMIT_STRUCTURED_DATA_TO_PROCESSINGS00Result)(results[0]));
    }
    
    /// <remarks/>
    public void submitStructuredDataToProcessingsAsync(string login, string password, string partnerCode, string messageType, byte[] data, string characterEncoding) {
        this.submitStructuredDataToProcessingsAsync(login, password, partnerCode, messageType, data, characterEncoding, null);
    }
    
    /// <remarks/>
    public void submitStructuredDataToProcessingsAsync(string login, string password, string partnerCode, string messageType, byte[] data, string characterEncoding, object userState) {
        if ((this.submitStructuredDataToProcessingsOperationCompleted == null)) {
            this.submitStructuredDataToProcessingsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsubmitStructuredDataToProcessingsOperationCompleted);
        }
        this.InvokeAsync("submitStructuredDataToProcessings", new object[] {
                    login,
                    password,
                    partnerCode,
                    messageType,
                    data,
                    characterEncoding}, this.submitStructuredDataToProcessingsOperationCompleted, userState);
    }
    
    private void OnsubmitStructuredDataToProcessingsOperationCompleted(object arg) {
        if ((this.submitStructuredDataToProcessingsCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.submitStructuredDataToProcessingsCompleted(this, new submitStructuredDataToProcessingsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://www.hardis.fr/reflexInterfacesWS", ResponseNamespace="http://www.hardis.fr/reflexInterfacesWS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("getStructuredDataFromProcessingsReturn")]
    public HWSITFAdeliaPrcnamGET_STRUCTURED_DATA_FROM_PROCESSINGS03Result getStructuredDataFromProcessings(string login, string password, string partnerCode, string messageType, int maximumNumberOfRetrievedMessages, string characterEncoding) {
        object[] results = this.Invoke("getStructuredDataFromProcessings", new object[] {
                    login,
                    password,
                    partnerCode,
                    messageType,
                    maximumNumberOfRetrievedMessages,
                    characterEncoding});
        return ((HWSITFAdeliaPrcnamGET_STRUCTURED_DATA_FROM_PROCESSINGS03Result)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetStructuredDataFromProcessings(string login, string password, string partnerCode, string messageType, int maximumNumberOfRetrievedMessages, string characterEncoding, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getStructuredDataFromProcessings", new object[] {
                    login,
                    password,
                    partnerCode,
                    messageType,
                    maximumNumberOfRetrievedMessages,
                    characterEncoding}, callback, asyncState);
    }
    
    /// <remarks/>
    public HWSITFAdeliaPrcnamGET_STRUCTURED_DATA_FROM_PROCESSINGS03Result EndgetStructuredDataFromProcessings(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((HWSITFAdeliaPrcnamGET_STRUCTURED_DATA_FROM_PROCESSINGS03Result)(results[0]));
    }
    
    /// <remarks/>
    public void getStructuredDataFromProcessingsAsync(string login, string password, string partnerCode, string messageType, int maximumNumberOfRetrievedMessages, string characterEncoding) {
        this.getStructuredDataFromProcessingsAsync(login, password, partnerCode, messageType, maximumNumberOfRetrievedMessages, characterEncoding, null);
    }
    
    /// <remarks/>
    public void getStructuredDataFromProcessingsAsync(string login, string password, string partnerCode, string messageType, int maximumNumberOfRetrievedMessages, string characterEncoding, object userState) {
        if ((this.getStructuredDataFromProcessingsOperationCompleted == null)) {
            this.getStructuredDataFromProcessingsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetStructuredDataFromProcessingsOperationCompleted);
        }
        this.InvokeAsync("getStructuredDataFromProcessings", new object[] {
                    login,
                    password,
                    partnerCode,
                    messageType,
                    maximumNumberOfRetrievedMessages,
                    characterEncoding}, this.getStructuredDataFromProcessingsOperationCompleted, userState);
    }
    
    private void OngetStructuredDataFromProcessingsOperationCompleted(object arg) {
        if ((this.getStructuredDataFromProcessingsCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getStructuredDataFromProcessingsCompleted(this, new getStructuredDataFromProcessingsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://www.hardis.fr/reflexInterfacesWS", ResponseNamespace="http://www.hardis.fr/reflexInterfacesWS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("getStructuredDataFromProcessingsBasedOnMessageNumberReturn")]
    public HWSITFAdeliaPrcnamGET_STRUCTURED_DATA_FROM_PROCESSINGS_BASED_ON_MESSAGE_NUMBER06Result getStructuredDataFromProcessingsBasedOnMessageNumber(string login, string password, string partnerCode, long messageNumber, string characterEncoding) {
        object[] results = this.Invoke("getStructuredDataFromProcessingsBasedOnMessageNumber", new object[] {
                    login,
                    password,
                    partnerCode,
                    messageNumber,
                    characterEncoding});
        return ((HWSITFAdeliaPrcnamGET_STRUCTURED_DATA_FROM_PROCESSINGS_BASED_ON_MESSAGE_NUMBER06Result)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetStructuredDataFromProcessingsBasedOnMessageNumber(string login, string password, string partnerCode, long messageNumber, string characterEncoding, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getStructuredDataFromProcessingsBasedOnMessageNumber", new object[] {
                    login,
                    password,
                    partnerCode,
                    messageNumber,
                    characterEncoding}, callback, asyncState);
    }
    
    /// <remarks/>
    public HWSITFAdeliaPrcnamGET_STRUCTURED_DATA_FROM_PROCESSINGS_BASED_ON_MESSAGE_NUMBER06Result EndgetStructuredDataFromProcessingsBasedOnMessageNumber(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((HWSITFAdeliaPrcnamGET_STRUCTURED_DATA_FROM_PROCESSINGS_BASED_ON_MESSAGE_NUMBER06Result)(results[0]));
    }
    
    /// <remarks/>
    public void getStructuredDataFromProcessingsBasedOnMessageNumberAsync(string login, string password, string partnerCode, long messageNumber, string characterEncoding) {
        this.getStructuredDataFromProcessingsBasedOnMessageNumberAsync(login, password, partnerCode, messageNumber, characterEncoding, null);
    }
    
    /// <remarks/>
    public void getStructuredDataFromProcessingsBasedOnMessageNumberAsync(string login, string password, string partnerCode, long messageNumber, string characterEncoding, object userState) {
        if ((this.getStructuredDataFromProcessingsBasedOnMessageNumberOperationCompleted == null)) {
            this.getStructuredDataFromProcessingsBasedOnMessageNumberOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetStructuredDataFromProcessingsBasedOnMessageNumberOperationCompleted);
        }
        this.InvokeAsync("getStructuredDataFromProcessingsBasedOnMessageNumber", new object[] {
                    login,
                    password,
                    partnerCode,
                    messageNumber,
                    characterEncoding}, this.getStructuredDataFromProcessingsBasedOnMessageNumberOperationCompleted, userState);
    }
    
    private void OngetStructuredDataFromProcessingsBasedOnMessageNumberOperationCompleted(object arg) {
        if ((this.getStructuredDataFromProcessingsBasedOnMessageNumberCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getStructuredDataFromProcessingsBasedOnMessageNumberCompleted(this, new getStructuredDataFromProcessingsBasedOnMessageNumberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.hardis.fr/reflexInterfacesWS")]
public partial class HWSITFAdeliaPrcnamSUBMIT_STRUCTURED_DATA_TO_PROCESSINGS00Result {
    
    private HWSITFAdeliaLstnam00P_O_ANOMALIES00PrcnamSUBMIT_STRUCTURED_DATA_TO_PROCESSINGS01Agglst[] anomaliesField;
    
    private HWSITFAdeliaLstnam0000P_O_ERREURS01PrcnamSUBMIT_STRUCTURED_DATA_TO_PROCESSINGS02Agglst[] errorsField;
    
    private System.Nullable<int> incorporationNumberField;
    
    private System.Nullable<long> messageNumberField;
    
    private string messageStateWordingField;
    
    private string messageStatusCodeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
    [System.Xml.Serialization.XmlArrayItemAttribute("item", IsNullable=false)]
    public HWSITFAdeliaLstnam00P_O_ANOMALIES00PrcnamSUBMIT_STRUCTURED_DATA_TO_PROCESSINGS01Agglst[] anomalies {
        get {
            return this.anomaliesField;
        }
        set {
            this.anomaliesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
    [System.Xml.Serialization.XmlArrayItemAttribute("item", IsNullable=false)]
    public HWSITFAdeliaLstnam0000P_O_ERREURS01PrcnamSUBMIT_STRUCTURED_DATA_TO_PROCESSINGS02Agglst[] errors {
        get {
            return this.errorsField;
        }
        set {
            this.errorsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<int> incorporationNumber {
        get {
            return this.incorporationNumberField;
        }
        set {
            this.incorporationNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<long> messageNumber {
        get {
            return this.messageNumberField;
        }
        set {
            this.messageNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string messageStateWording {
        get {
            return this.messageStateWordingField;
        }
        set {
            this.messageStateWordingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string messageStatusCode {
        get {
            return this.messageStatusCodeField;
        }
        set {
            this.messageStatusCodeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.hardis.fr/reflexInterfacesWS")]
public partial class HWSITFAdeliaLstnam00P_O_ANOMALIES00PrcnamSUBMIT_STRUCTURED_DATA_TO_PROCESSINGS01Agglst {
    
    private string aNOMALYCODEField;
    
    private string aNOMALYMESSAGEField;
    
    private string aPPLICATIONCODEField;
    
    private string iNTERFACECODEField;
    
    private string sECTIONCODEField;
    
    private System.Nullable<int> sEQUENCENUMBERField;
    
    private string sEVERITYCODEField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string ANOMALYCODE {
        get {
            return this.aNOMALYCODEField;
        }
        set {
            this.aNOMALYCODEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string ANOMALYMESSAGE {
        get {
            return this.aNOMALYMESSAGEField;
        }
        set {
            this.aNOMALYMESSAGEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string APPLICATIONCODE {
        get {
            return this.aPPLICATIONCODEField;
        }
        set {
            this.aPPLICATIONCODEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string INTERFACECODE {
        get {
            return this.iNTERFACECODEField;
        }
        set {
            this.iNTERFACECODEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string SECTIONCODE {
        get {
            return this.sECTIONCODEField;
        }
        set {
            this.sECTIONCODEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<int> SEQUENCENUMBER {
        get {
            return this.sEQUENCENUMBERField;
        }
        set {
            this.sEQUENCENUMBERField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string SEVERITYCODE {
        get {
            return this.sEVERITYCODEField;
        }
        set {
            this.sEVERITYCODEField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.hardis.fr/reflexInterfacesWS")]
public partial class HWSITFAdeliaLstnam0000P_O_ERREURS04PrcnamGET_STRUCTURED_DATA_FROM_PROCESSINGS_BASED_ON_MESSAGE_NUMBER07Agglst {
    
    private string eRRORCODEField;
    
    private string eRRORMESSAGEField;
    
    private string sTEPCODEField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string ERRORCODE {
        get {
            return this.eRRORCODEField;
        }
        set {
            this.eRRORCODEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string ERRORMESSAGE {
        get {
            return this.eRRORMESSAGEField;
        }
        set {
            this.eRRORMESSAGEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string STEPCODE {
        get {
            return this.sTEPCODEField;
        }
        set {
            this.sTEPCODEField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.hardis.fr/reflexInterfacesWS")]
public partial class HWSITFAdeliaPrcnamGET_STRUCTURED_DATA_FROM_PROCESSINGS_BASED_ON_MESSAGE_NUMBER06Result {
    
    private byte[] dataField;
    
    private HWSITFAdeliaLstnam0000P_O_ERREURS04PrcnamGET_STRUCTURED_DATA_FROM_PROCESSINGS_BASED_ON_MESSAGE_NUMBER07Agglst[] errorsField;
    
    private System.Nullable<long> messageNumberUsedField;
    
    private string messageTypeField;
    
    private string partnerCodeUsedField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)]
    public byte[] data {
        get {
            return this.dataField;
        }
        set {
            this.dataField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
    [System.Xml.Serialization.XmlArrayItemAttribute("item", IsNullable=false)]
    public HWSITFAdeliaLstnam0000P_O_ERREURS04PrcnamGET_STRUCTURED_DATA_FROM_PROCESSINGS_BASED_ON_MESSAGE_NUMBER07Agglst[] errors {
        get {
            return this.errorsField;
        }
        set {
            this.errorsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<long> messageNumberUsed {
        get {
            return this.messageNumberUsedField;
        }
        set {
            this.messageNumberUsedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string messageType {
        get {
            return this.messageTypeField;
        }
        set {
            this.messageTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string partnerCodeUsed {
        get {
            return this.partnerCodeUsedField;
        }
        set {
            this.partnerCodeUsedField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.hardis.fr/reflexInterfacesWS")]
public partial class HWSITFAdeliaLstnamP_O_MSG_TRAITES02PrcnamGET_STRUCTURED_DATA_FROM_PROCESSINGS04Agglst {
    
    private byte[] dATAField;
    
    private System.Nullable<long> mESSAGENUMBERField;
    
    private string mESSAGETYPEField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)]
    public byte[] DATA {
        get {
            return this.dATAField;
        }
        set {
            this.dATAField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<long> MESSAGENUMBER {
        get {
            return this.mESSAGENUMBERField;
        }
        set {
            this.mESSAGENUMBERField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string MESSAGETYPE {
        get {
            return this.mESSAGETYPEField;
        }
        set {
            this.mESSAGETYPEField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.hardis.fr/reflexInterfacesWS")]
public partial class HWSITFAdeliaLstnam0000P_O_ERREURS03PrcnamGET_STRUCTURED_DATA_FROM_PROCESSINGS05Agglst {
    
    private string eRRORCODEField;
    
    private string eRRORMESSAGEField;
    
    private string sTEPCODEField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string ERRORCODE {
        get {
            return this.eRRORCODEField;
        }
        set {
            this.eRRORCODEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string ERRORMESSAGE {
        get {
            return this.eRRORMESSAGEField;
        }
        set {
            this.eRRORMESSAGEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string STEPCODE {
        get {
            return this.sTEPCODEField;
        }
        set {
            this.sTEPCODEField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.hardis.fr/reflexInterfacesWS")]
public partial class HWSITFAdeliaPrcnamGET_STRUCTURED_DATA_FROM_PROCESSINGS03Result {
    
    private HWSITFAdeliaLstnam0000P_O_ERREURS03PrcnamGET_STRUCTURED_DATA_FROM_PROCESSINGS05Agglst[] errorsField;
    
    private HWSITFAdeliaLstnamP_O_MSG_TRAITES02PrcnamGET_STRUCTURED_DATA_FROM_PROCESSINGS04Agglst[] messagesField;
    
    private string partnerCodeUsedField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
    [System.Xml.Serialization.XmlArrayItemAttribute("item", IsNullable=false)]
    public HWSITFAdeliaLstnam0000P_O_ERREURS03PrcnamGET_STRUCTURED_DATA_FROM_PROCESSINGS05Agglst[] errors {
        get {
            return this.errorsField;
        }
        set {
            this.errorsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
    [System.Xml.Serialization.XmlArrayItemAttribute("item", IsNullable=false)]
    public HWSITFAdeliaLstnamP_O_MSG_TRAITES02PrcnamGET_STRUCTURED_DATA_FROM_PROCESSINGS04Agglst[] messages {
        get {
            return this.messagesField;
        }
        set {
            this.messagesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string partnerCodeUsed {
        get {
            return this.partnerCodeUsedField;
        }
        set {
            this.partnerCodeUsedField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.hardis.fr/reflexInterfacesWS")]
public partial class HWSITFAdeliaLstnam0000P_O_ERREURS01PrcnamSUBMIT_STRUCTURED_DATA_TO_PROCESSINGS02Agglst {
    
    private string eRRORCODEField;
    
    private string eRRORMESSAGEField;
    
    private string sTEPCODEField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string ERRORCODE {
        get {
            return this.eRRORCODEField;
        }
        set {
            this.eRRORCODEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string ERRORMESSAGE {
        get {
            return this.eRRORMESSAGEField;
        }
        set {
            this.eRRORMESSAGEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string STEPCODE {
        get {
            return this.sTEPCODEField;
        }
        set {
            this.sTEPCODEField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void submitStructuredDataToProcessingsCompletedEventHandler(object sender, submitStructuredDataToProcessingsCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class submitStructuredDataToProcessingsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal submitStructuredDataToProcessingsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public HWSITFAdeliaPrcnamSUBMIT_STRUCTURED_DATA_TO_PROCESSINGS00Result Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((HWSITFAdeliaPrcnamSUBMIT_STRUCTURED_DATA_TO_PROCESSINGS00Result)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void getStructuredDataFromProcessingsCompletedEventHandler(object sender, getStructuredDataFromProcessingsCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getStructuredDataFromProcessingsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getStructuredDataFromProcessingsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public HWSITFAdeliaPrcnamGET_STRUCTURED_DATA_FROM_PROCESSINGS03Result Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((HWSITFAdeliaPrcnamGET_STRUCTURED_DATA_FROM_PROCESSINGS03Result)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void getStructuredDataFromProcessingsBasedOnMessageNumberCompletedEventHandler(object sender, getStructuredDataFromProcessingsBasedOnMessageNumberCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getStructuredDataFromProcessingsBasedOnMessageNumberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getStructuredDataFromProcessingsBasedOnMessageNumberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public HWSITFAdeliaPrcnamGET_STRUCTURED_DATA_FROM_PROCESSINGS_BASED_ON_MESSAGE_NUMBER06Result Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((HWSITFAdeliaPrcnamGET_STRUCTURED_DATA_FROM_PROCESSINGS_BASED_ON_MESSAGE_NUMBER06Result)(this.results[0]));
        }
    }
}
